// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//     return (
//         <html lang="en">
//             <body
//                 className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//             >
//                 {children}
//             </body>
//         </html>
//     );
// }



// -----------------------------

import { Playfair_Display, Fraunces, IBM_Plex_Sans, Nunito } from "next/font/google";

import "./globals.css";
import Navbar from "./components/home-page/Navbar";
import Footer from "./components/home-page/Footer";
// import Footer from "./components/home-page/Footer";

const ibm = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
});


const playfair = Playfair_Display({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const fraunces = Fraunces({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-fraunces",
});


const nunito = Nunito({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">

            <body className={fraunces.className}>
                <Navbar />
                {/* <Test/> */}
                {children}
                <Footer />

            </body>
        </html>
    );
}
